version: "3.9"

services:
  minerva:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: .env
    networks:
      - minerva-network
    restart:
      always

networks:
  minerva-network:
