name: Build Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: runner / Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Set up Node.js
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
