name: ESLint

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: runner / ESLint lint actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2
      - name: Set up Node.js
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
